//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanM.HrSystem.DataLayer.DataEntries.Common;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class ApplicationSettingsEntries : Havit.Data.Patterns.DataEntries.DataEntries<DanM.HrSystem.Model.Common.ApplicationSettings>, IApplicationSettingsEntries 
{
	private DanM.HrSystem.Model.Common.ApplicationSettings current;

	public DanM.HrSystem.Model.Common.ApplicationSettings Current => current ??= GetEntry(DanM.HrSystem.Model.Common.ApplicationSettings.Entry.Current);

	public ApplicationSettingsEntries(DanM.HrSystem.DataLayer.Repositories.Common.IApplicationSettingsRepository repository)
		: base(repository)
	{
	}
}
