//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.Patterns.DataSources;

namespace DanM.HrSystem.DataLayer.DataSources.Persons;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public interface IPersonDataSource : IDataSource<DanM.HrSystem.Model.Persons.Person>
{
}
