//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanM.HrSystem.DataLayer.DataEntries.Localizations;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class LanguageEntries : Havit.Data.Patterns.DataEntries.DataEntries<DanM.HrSystem.Model.Localizations.Language>, ILanguageEntries 
{
	private DanM.HrSystem.Model.Localizations.Language czech;
	private DanM.HrSystem.Model.Localizations.Language english;

	public DanM.HrSystem.Model.Localizations.Language Czech => czech ??= GetEntry(DanM.HrSystem.Model.Localizations.Language.Entry.Czech);
	public DanM.HrSystem.Model.Localizations.Language English => english ??= GetEntry(DanM.HrSystem.Model.Localizations.Language.Entry.English);

	public LanguageEntries(DanM.HrSystem.DataLayer.Repositories.Localizations.ILanguageRepository repository)
		: base(repository)
	{
	}
}
