//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace DanM.HrSystem.DataLayer.DataSources.Persons.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakePersonDataSource : FakeDataSource<DanM.HrSystem.Model.Persons.Person>, DanM.HrSystem.DataLayer.DataSources.Persons.IPersonDataSource
{
	public FakePersonDataSource(params DanM.HrSystem.Model.Persons.Person[] data)
		: this((IEnumerable<DanM.HrSystem.Model.Persons.Person>)data)
	{			
	}

	public FakePersonDataSource(IEnumerable<DanM.HrSystem.Model.Persons.Person> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
