//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace DanM.HrSystem.DataLayer.DataSources.Common.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeApplicationSettingsDataSource : FakeDataSource<DanM.HrSystem.Model.Common.ApplicationSettings>, DanM.HrSystem.DataLayer.DataSources.Common.IApplicationSettingsDataSource
{
	public FakeApplicationSettingsDataSource(params DanM.HrSystem.Model.Common.ApplicationSettings[] data)
		: this((IEnumerable<DanM.HrSystem.Model.Common.ApplicationSettings>)data)
	{			
	}

	public FakeApplicationSettingsDataSource(IEnumerable<DanM.HrSystem.Model.Common.ApplicationSettings> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
