//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanM.HrSystem.Contracts.ModelMetadata.Employees;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public static class EmployeeMetadata
{
	public const int EmailMaxLength = 255;
	public const int FirstNameMaxLength = 30;
	public const int LastNameMaxLength = 30;
	public const int PersonalNumberMaxLength = 10;
}
