//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace DanM.HrSystem.DataLayer.DataSources.Employees.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeEmployeeDataSource : FakeDataSource<DanM.HrSystem.Model.Employees.Employee>, DanM.HrSystem.DataLayer.DataSources.Employees.IEmployeeDataSource
{
	public FakeEmployeeDataSource(params DanM.HrSystem.Model.Employees.Employee[] data)
		: this((IEnumerable<DanM.HrSystem.Model.Employees.Employee>)data)
	{			
	}

	public FakeEmployeeDataSource(IEnumerable<DanM.HrSystem.Model.Employees.Employee> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
