//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace DanM.HrSystem.DataLayer.DataSources.Agreements.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeAgreementDataSource : FakeDataSource<DanM.HrSystem.Model.Agreements.Agreement>, DanM.HrSystem.DataLayer.DataSources.Agreements.IAgreementDataSource
{
	public FakeAgreementDataSource(params DanM.HrSystem.Model.Agreements.Agreement[] data)
		: this((IEnumerable<DanM.HrSystem.Model.Agreements.Agreement>)data)
	{			
	}

	public FakeAgreementDataSource(IEnumerable<DanM.HrSystem.Model.Agreements.Agreement> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
